:impressions:
  :host: 'mq.revieworld.com'
  :port: 13000
:non_impressions:
  :host: 'mq.revieworld.com'
  :port: 13001
:misses:
  :host: 'mq.revieworld.com'
  :port: 13002
:clickthrus: 
  :host: 'mq.revieworld.com'
  :port: 13003
:was_helpfuls:
  :host: 'mq.revieworld.com'
  :port: 13004
:purchase_queue:
  :host: 'mq.revieworld.com'
  :port: 13005
:reevoomark_exceptions:
  :host: 'mq.revieworld.com'
  :port: 13006
:revieworld_exceptions:
  :host: 'mq.revieworld.com'
  :port: 13007
:product_ranking:
  :host: 'mq.revieworld.com'
  :port: 13008
:published_reviews:
  :host: 'mq.revieworld.com'
  :port: 13009
:reevoo_exceptions:
  :host: 'mq.revieworld.com'
  :port: 13010